## Tokenization Functions

In [3]:
## Paragraph -> Sentences 

from nltk.tokenize import sent_tokenize
def sentence_tokenize(corpus):
    sentences = sent_tokenize(corpus)
    ## print
    for sentence in sentences:
        print("sentence = ",sentence)
    return None

corpus = """Hello I am Trishansh and I am
all good. How are You? What are you doing ?"""
sentence_tokenize(corpus)

sentence =  Hello I am Trishansh and I am
all good.
sentence =  How are You?
sentence =  What are you doing ?


In [4]:
## Sentence -> words 

from nltk.tokenize import word_tokenize
def word_tokenizer(senetence):
    words = word_tokenize(senetence)
    ## print
    for word in words :
        print("Word = ",word )
    return None 

sentence = "Trishansh is an AI'ML, and DS Lead at GDG SDSF.He is good."
word_tokenizer(sentence)

Word =  Trishansh
Word =  is
Word =  an
Word =  AI'ML
Word =  ,
Word =  and
Word =  DS
Word =  Lead
Word =  at
Word =  GDG
Word =  SDSF.He
Word =  is
Word =  good
Word =  .


In [5]:
## Sentence -> words using Tree Bank Method

from nltk.tokenize import TreebankWordTokenizer
def word_tokenizer(senetence):
    tokenizer = TreebankWordTokenizer()
    words = tokenizer.tokenize(sentence)
    ## print
    for word in words :
        print("Word = ",word )
    return None 

sentence = "Trishansh is an AI'ML, and DS Lead at GDG SDSF.He is good."
word_tokenizer(sentence)

Word =  Trishansh
Word =  is
Word =  an
Word =  AI'ML
Word =  ,
Word =  and
Word =  DS
Word =  Lead
Word =  at
Word =  GDG
Word =  SDSF.He
Word =  is
Word =  good
Word =  .


## Stemming Functions

In [6]:
## Porter Stemmer 

from nltk import PorterStemmer
def porter_stemmer(lst):
    stemmer = PorterStemmer()
    for i in lst:
        print(i," ----> ",stemmer.stem(i))
    return None 

lst = ["going","Gone","having","Sportingly","history"]
porter_stemmer(lst)

going  ---->  go
Gone  ---->  gone
having  ---->  have
Sportingly  ---->  sportingli
history  ---->  histori


In [7]:
## Snowball Stemmer 

from nltk import SnowballStemmer
def snowball_stemmer(lst):
    snow_stem = SnowballStemmer("english")
    for i in lst : 
        print(i," ----> ",snow_stem.stem(i))
    return None 

snowball_stemmer(lst)

going  ---->  go
Gone  ---->  gone
having  ---->  have
Sportingly  ---->  sport
history  ---->  histori


In [8]:
## Regular Expression Stemmer Class 

from nltk import RegexpStemmer
def regexp_fun(expression,lst):
    regexp = RegexpStemmer(expression,min=4)
    for i in lst :
        print(i," ----> ",regexp.stem(i))
    return None
new_lst = ["eaten","eats","beats","ing_ing","seats"]
regexp_fun("ing$|s$|en$",lst)
regexp_fun("ing$|s$|en$",new_lst)

going  ---->  go
Gone  ---->  Gone
having  ---->  hav
Sportingly  ---->  Sportingly
history  ---->  history
eaten  ---->  eat
eats  ---->  eat
beats  ---->  beat
ing_ing  ---->  ing_
seats  ---->  seat


## Lemmatization Functions 

In [9]:
from nltk import WordNetLemmatizer
def lemmatization_fun(lst,pos):
    lemmatizer = WordNetLemmatizer()
    for i in lst : 
        print(i," ----> ",lemmatizer.lemmatize(i,pos=pos))
    return None 

## Pos ( part of speech : noun(n) , verb(v) ,adverb(r) , adjective(a) )
lemmatization_fun(lst,"v")
lemmatization_fun(lst,"n")

going  ---->  go
Gone  ---->  Gone
having  ---->  have
Sportingly  ---->  Sportingly
history  ---->  history
going  ---->  going
Gone  ---->  Gone
having  ---->  having
Sportingly  ---->  Sportingly
history  ---->  history


## Stopwords Functions 

In [10]:
## Printing Stopwords

from nltk.corpus import stopwords
def stopwords_fun(lang):
    print(stopwords.words(lang))
    return None 

stopwords_fun("english")
stopwords_fun("arabic")
stopwords_fun("french")

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', '

In [11]:
## Speech Of DR APJ Abdul Kalam
paragraph = """I have three visions for India. In 3000 years of our history, people from all over 
               the world have come and invaded us, captured our lands, conquered our minds. 
               From Alexander onwards, the Greeks, the Turks, the Moguls, the Portuguese, the British,
               the French, the Dutch, all of them came and looted us, took over what was ours. 
               Yet we have not done this to any other nation. We have not conquered anyone. 
               We have not grabbed their land, their culture, 
               their history and tried to enforce our way of life on them. 
               Why? Because we respect the freedom of others.That is why my 
               first vision is that of freedom. I believe that India got its first vision of 
               this in 1857, when we started the War of Independence. It is this freedom that
               we must protect and nurture and build on. If we are not free, no one will respect us.
               My second vision for India’s development. For fifty years we have been a developing nation.
               It is time we see ourselves as a developed nation. We are among the top 5 nations of the world
               in terms of GDP. We have a 10 percent growth rate in most areas. Our poverty levels are falling.
               Our achievements are being globally recognised today. Yet we lack the self-confidence to
               see ourselves as a developed nation, self-reliant and self-assured. Isn’t this incorrect?
               I have a third vision. India must stand up to the world. Because I believe that unless India 
               stands up to the world, no one will respect us. Only strength respects strength. We must be 
               strong not only as a military power but also as an economic power. Both must go hand-in-hand. 
               My good fortune was to have worked with three great minds. Dr. Vikram Sarabhai of the Dept. of 
               space, Professor Satish Dhawan, who succeeded him and Dr. Brahm Prakash, father of nuclear material.
               I was lucky to have worked with all three of them closely and consider this the great opportunity of my life. 
               I see four milestones in my career"""

In [12]:
## Removing Stopwords using different techniques 

from nltk import sent_tokenize
from nltk import word_tokenize 
from nltk.corpus import stopwords 
from nltk import PorterStemmer
from nltk import SnowballStemmer
from nltk import WordNetLemmatizer

port_stemmer = PorterStemmer()
snow_stemmer = SnowballStemmer("english")
Lemmatizer = WordNetLemmatizer()

def Stop_words_remove_fun(corpus,stemmer):
    ## paragraph --> sentence
    sentences = sent_tokenize(corpus)
    
    for i in range(len(sentences)):
        ## lowering and sentence --> words
        sentences[i] = sentences[i].lower()
        words = word_tokenize(sentences[i])
        ## checking for stopwords 
        if stemmer == "Porter_Stemmer":
            words = [port_stemmer.stem(word) for word in words if word not in set(stopwords.words("english"))]
        elif stemmer == "Snowball_Stemmer":
            words = [snow_stemmer.stem(word) for word in words if word not in set(stopwords.words("english"))]
        elif stemmer == "Lemmatizer":
            words = [Lemmatizer.lemmatize(word,pos="v") for word in words if word not in set(stopwords.words("english"))]
        ## Creating sentence using these words 
        sentences[i] = " ".join(words)
    print(sentences)
   
Stop_words_remove_fun(paragraph,"Porter_Stemmer")
Stop_words_remove_fun(paragraph,"Snowball_Stemmer")
Stop_words_remove_fun(paragraph,"Lemmatizer")

['three vision india .', '3000 year histori , peopl world come invad us , captur land , conquer mind .', 'alexand onward , greek , turk , mogul , portugues , british , french , dutch , came loot us , took .', 'yet done nation .', 'conquer anyon .', 'grab land , cultur , histori tri enforc way life .', '?', 'respect freedom others.that first vision freedom .', 'believ india got first vision 1857 , start war independ .', 'freedom must protect nurtur build .', 'free , one respect us .', 'second vision india ’ develop .', 'fifti year develop nation .', 'time see develop nation .', 'among top 5 nation world term gdp .', '10 percent growth rate area .', 'poverti level fall .', 'achiev global recognis today .', 'yet lack self-confid see develop nation , self-reli self-assur .', '’ incorrect ?', 'third vision .', 'india must stand world .', 'believ unless india stand world , one respect us .', 'strength respect strength .', 'must strong militari power also econom power .', 'must go hand-in-han

## BOW Functions

In [13]:
import nltk
import re 

In [14]:
from nltk import PorterStemmer
from nltk.corpus import stopwords 
import pandas as pd 

messages = pd.read_csv("SMSSpamCollection",sep="\t",names=["labels","message"])

stemmer = PorterStemmer()

corpus = []
for i in range(len(messages)):
    review = re.sub("[^a-zA-z]"," ",messages["message"][i])
    review = review.lower()
    review = review.split()
    review = [stemmer.stem(word) for word in review if word not in set(stopwords.words("english"))]
    review = " ".join(review)
    corpus.append(review)

corpus


['go jurong point crazi avail bugi n great world la e buffet cine got amor wat',
 'ok lar joke wif u oni',
 'free entri wkli comp win fa cup final tkt st may text fa receiv entri question std txt rate c appli',
 'u dun say earli hor u c alreadi say',
 'nah think goe usf live around though',
 'freemsg hey darl week word back like fun still tb ok xxx std chg send rcv',
 'even brother like speak treat like aid patent',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press copi friend callertun',
 'winner valu network custom select receivea prize reward claim call claim code kl valid hour',
 'mobil month u r entitl updat latest colour mobil camera free call mobil updat co free',
 'gonna home soon want talk stuff anymor tonight k cri enough today',
 'six chanc win cash pound txt csh send cost p day day tsandc appli repli hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw',
 'search right word thank breather

In [15]:
## Count Vectorizer 

from sklearn.feature_extraction.text import CountVectorizer

def cv_fun(max,binary=False):
    cv = CountVectorizer(max_features=max,binary=binary)
    X = cv.fit_transform(corpus).toarray()
    print(cv.vocabulary_)
    print("shape =", X.shape)
    return X 

cv_fun(1000,True)

{'go': np.int64(332), 'point': np.int64(650), 'crazi': np.int64(171), 'avail': np.int64(50), 'great': np.int64(344), 'world': np.int64(975), 'la': np.int64(441), 'got': np.int64(341), 'wat': np.int64(937), 'ok': np.int64(597), 'lar': np.int64(446), 'joke': np.int64(426), 'wif': np.int64(958), 'free': np.int64(302), 'entri': np.int64(251), 'wkli': np.int64(969), 'comp': np.int64(148), 'win': np.int64(961), 'cup': np.int64(175), 'final': np.int64(285), 'st': np.int64(811), 'may': np.int64(511), 'text': np.int64(852), 'receiv': np.int64(691), 'question': np.int64(676), 'std': np.int64(816), 'txt': np.int64(899), 'rate': np.int64(682), 'appli': np.int64(38), 'dun': np.int64(231), 'say': np.int64(737), 'earli': np.int64(234), 'alreadi': np.int64(22), 'nah': np.int64(564), 'think': np.int64(858), 'goe': np.int64(334), 'usf': np.int64(917), 'live': np.int64(477), 'around': np.int64(42), 'though': np.int64(862), 'freemsg': np.int64(303), 'hey': np.int64(371), 'week': np.int64(946), 'word': np.

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [16]:
## Count Vectorizer with n_grams 

from sklearn.feature_extraction.text import CountVectorizer

def cv_fun(max,a,b,binary=False):
    cv = CountVectorizer(max_features=max,binary=binary,ngram_range=(a,b))
    X = cv.fit_transform(corpus).toarray()
    print(cv.vocabulary_)
    print("shape =", X.shape)
    return X 

cv_fun(1000,2,2,True)

{'ok lar': np.int64(598), 'free entri': np.int64(235), 'entri wkli': np.int64(213), 'std txt': np.int64(757), 'txt rate': np.int64(854), 'rate appli': np.int64(683), 'like fun': np.int64(417), 'per request': np.int64(636), 'set callertun': np.int64(729), 'callertun caller': np.int64(83), 'caller press': np.int64(81), 'press copi': np.int64(675), 'copi friend': np.int64(154), 'friend callertun': np.int64(242), 'claim call': np.int64(112), 'call claim': np.int64(54), 'claim code': np.int64(113), 'valid hour': np.int64(906), 'entitl updat': np.int64(211), 'updat latest': np.int64(869), 'latest colour': np.int64(403), 'free call': np.int64(233), 'call mobil': np.int64(67), 'mobil updat': np.int64(522), 'updat co': np.int64(868), 'co free': np.int64(124), 'want talk': np.int64(940), 'chanc win': np.int64(106), 'win cash': np.int64(971), 'repli hl': np.int64(693), 'hl info': np.int64(331), 'week free': np.int64(956), 'txt word': np.int64(856), 'dont miss': np.int64(192), 'ha ha': np.int64(31

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

## TF-IDF Function

In [ ]:
## Tfidf vectorizer 

from sklearn.feature_extraction.text import TfidfVectorizer

def tf_idf_fun(max):
    tfidf = TfidfVectorizer(max_features=max)
    X = tfidf.fit_transform(corpus).toarray()
    print(tfidf.vocabulary_)
    print("shape =" ,X.shape)
    return X

tf_idf_fun(1000)

{'go': np.int64(338), 'point': np.int64(651), 'crazi': np.int64(175), 'avail': np.int64(54), 'great': np.int64(351), 'world': np.int64(975), 'la': np.int64(448), 'got': np.int64(347), 'wat': np.int64(934), 'ok': np.int64(598), 'lar': np.int64(453), 'joke': np.int64(433), 'wif': np.int64(956), 'free': np.int64(306), 'entri': np.int64(253), 'wkli': np.int64(968), 'comp': np.int64(150), 'win': np.int64(959), 'cup': np.int64(179), 'final': np.int64(288), 'st': np.int64(805), 'may': np.int64(514), 'text': np.int64(845), 'receiv': np.int64(694), 'question': np.int64(677), 'std': np.int64(810), 'txt': np.int64(894), 'rate': np.int64(684), 'appli': np.int64(41), 'dun': np.int64(232), 'say': np.int64(738), 'earli': np.int64(235), 'alreadi': np.int64(25), 'nah': np.int64(564), 'think': np.int64(851), 'goe': np.int64(340), 'usf': np.int64(913), 'live': np.int64(481), 'around': np.int64(46), 'though': np.int64(855), 'freemsg': np.int64(307), 'hey': np.int64(378), 'week': np.int64(943), 'word': np.

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [21]:
## Tfidf vectorizer with lowering case , stopwords and n-grams 

from sklearn.feature_extraction.text import TfidfVectorizer

def tf_idf_fun(max,a,b):
    tfidf = TfidfVectorizer(max_features=max,lowercase=True,stop_words="english",ngram_range=(a,b))
    X = tfidf.fit_transform(corpus).toarray()
    print(tfidf.vocabulary_)
    print("shape =" ,X.shape)
    return X

tf_idf_fun(1000,2,3)

{'free entri': np.int64(236), 'entri wkli': np.int64(210), 'cup final': np.int64(158), 'std txt': np.int64(757), 'txt rate': np.int64(848), 'rate appli': np.int64(649), 'free entri wkli': np.int64(238), 'std txt rate': np.int64(758), 'txt rate appli': np.int64(849), 'like fun': np.int64(386), 'set callertun': np.int64(721), 'callertun caller': np.int64(63), 'caller press': np.int64(59), 'press copi': np.int64(631), 'copi friend': np.int64(139), 'friend callertun': np.int64(252), 'set callertun caller': np.int64(722), 'callertun caller press': np.int64(64), 'caller press copi': np.int64(60), 'press copi friend': np.int64(632), 'copi friend callertun': np.int64(140), 'claim code': np.int64(93), 'entitl updat': np.int64(206), 'updat latest': np.int64(860), 'latest colour': np.int64(372), 'free mobil': np.int64(242), 'mobil updat': np.int64(500), 'updat free': np.int64(859), 'entitl updat latest': np.int64(207), 'updat latest colour': np.int64(861), 'free mobil updat': np.int64(243), 'mobi

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

## POS ( Part of Speech ) Tagging 

In [ ]:
## Function to assign pos tag to each word in sentence 

## nltk.download('averaged_perceptron_tagger_eng')

def postag_fun(sentence):
    ## converting sentence into words
    sentence = sentence.split()
    return nltk.pos_tag(sentence)

postag_fun("These NLP functions are created by Trishansh")

[('These', 'DT'),
 ('NLP', 'NNP'),
 ('functions', 'NNS'),
 ('are', 'VBP'),
 ('created', 'VBN'),
 ('by', 'IN'),
 ('Trishansh', 'NNP')]

## Named Entity Recognition 

In [45]:
## Function for applying named entity recognition 

## nltk.download('maxent_ne_chunker_tab')
## nltk.download('words')

def named_entity_fun(sentence):
    ## converting sentence into words
    sentence = sentence.split()
    ## applying pos_tag
    tagged_elements  = nltk.pos_tag(sentence)
    return nltk.ne_chunk(tagged_elements).draw()

named_entity_fun("These NLP functions are created by Trishansh")

## output 
## --> All the words are visually represented along with their pos tags